---
- name: Lighthouse | Create lighthouse config
  become: true
  ansible.builtin.template:
    src: lighthouse.conf.j2
    dest: /etc/nginx/conf.d/default.conf
    mode: "0644"
  notify: Reload-nginx
